SIRHCoreWeb/Areas/SIRH/Controllers/FraisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SIRHCoreDomain;
using SIRHCoreService;
using System.Data;
using Microsoft.AspNetCore.Authorization;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using SIRHCoreWeb.Data;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace SIRHCoreWeb.Areas.SIRH.Controllers
{

    [Area("SIRH")]
    [Route("SIRH/[controller]/[action]")]
    [Authorize(Roles = "Collaborateur")]

    public class FraisController : Controller
    {
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                service.Dispose();
            }
            base.Dispose(disposing);
        }

        private readonly UserManager<IdentityUser> userManager;

        public FraisController(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            service = new FraisService();
        }
        IFraisService service = null;

        /*******************************************************/


        [Authorize]
        public IActionResult CreateN()

        {

            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult CreateN(NoteDeFrais f)


        {
            f.Userid = this.User.Identity.Name;
             const string statut = "à valider";

            if (ModelState.IsValid)
            {

                f.Userid = this.User.Identity.Name;
                 f.Statut = statut;

                service.CreateFrais(f);


                return RedirectToAction("Index");

            }
            return View(f);
        }
        //********************Index******************//
        [Authorize]
        public IActionResult Index(string search)
        {
            if (search == null)
            {
                string user = User.Identity.Name;
                var Conges = service.GetFraisByUser(user);

                return View(Conges);
            }
            else
            {
                var Conges = service.GetFraisByStatut(search);
                return View(Conges);
            }

        }
        //************Edit********************//
        [Authorize]
        public IActionResult Edit(int id)
        {
            NoteDeFrais c = service.GetFrais(id);
            return View(c);

        }

        [HttpPost]

        public IActionResult Edit(NoteDeFrais f)
        {

            //const string statut = "à valider";
        

            if (ModelState.IsValid)
            {
                //c.Statut = statut;
                f.Userid = User.Identity.Name;
                if (f.Statut == "à valider")
                {
                    service.UpdateFrais(f);

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["msg"] = "la demande est déjà validée, vous ne pouvez pas la modifier";

                    return View();
                }
            }

            return View(f);
        }


        /////*********************Delete************************//

        [Authorize]
        public IActionResult Delete(int id)
        {

            NoteDeFrais con = service.GetFrais(id);
            return View(con);
        }
        [HttpPost, ActionName("Delete")]

        public IActionResult DeleteFrais(int id)

        {

            try
            {
                if (ModelState.IsValid)
                {
                    NoteDeFrais conn = service.GetFrais(id);
                    service.DeleteFrais(conn);
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View();
        }
        ///***************************Details**************************///

        public IActionResult Details(int id)
        {

            NoteDeFrais conn = service.GetFrais(id);

            return View(conn);

        }






    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DeleteModel : PageModel
         
    {//injection du context
        
        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DeleteModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }
       
          
        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DetailModel : PageModel
    {//injection du context

        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DetailModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }

        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Views/Frais/Delete.cshtml
@model SIRHCoreDomain.NoteDeFrais

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center><h1><font color="#273746">Supprimer votre note de frais?! </font></h1></center>
    </div>
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt
                     _wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">
                    <div class="kt-wizard-v2__nav">

                        <!--doc: Remove "kt-wizard-v2__nav-items--clickable" class and also set 'clickableSteps: false' in the JS init to disable manually clicking step titles -->
                        <div class="kt-wizard-v2__nav-items kt-wizard-v2__nav-items--clickable">
                        </div>
                    </div>
                    <div>
                        <h4></h4>
                        <hr />

                        <h5><center>Voulez vous vraiment supprimer cette note de frais?</center></h5>
                        <div class="col-sm-9 " style="margin-left: 400px; margin-top: 50px;">
                            <dl class="row ">

                                <dt class="col-sm-2">

                                    <label>ID</label>
                                </dt>
                                <dd class="col-sm-10">

                                    @Html.DisplayFor(model => model.NoteDeFraisID)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Date de début</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Date)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Date de fin</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Type)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Type</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Montant)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Dureée(en jour)</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.nbrper)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Commentaire</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CommentaireF)
                                </dd>
                                <dt class="col-sm-2">
                                    <label>Justificatif</label>
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Justificatif)
                                </dd>

                            </dl>
                            @using (Html.BeginForm())
                            {

                            <p>
                                <div class="kt-form__actions">
                                    <input type="hidden" asp-for="NoteDeFrais.NoteDeFraisID" />
                                    <input type="submit" value="Supprimer" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2" />

                                    <input type="button" style="margin-left: 400px;" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2" value="Précédent" onclick="location.href='@Url.Action("Index", "Frais" )'" />

                                </div>
                                <!----input type="submit" value="Delete" /-->



                            </p>

                            }

                        </div>
                        <hr />

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

SIRHCoreWeb/Areas/SIRH/Views/Frais/Details.cshtml
@model SIRHCoreDomain.NoteDeFrais

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <link href="~/css/pages/wizard/wizard-2.css" rel="stylesheet" type="text/css" />

    <!--end::Page Custom Styles -->





    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-heading kt-heading--md">
            <center><h1><font color="#273746"> Note de frais </font></h1> </center>
        </div>
        <div class="kt-portlet">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                    <!----div class="kt-grid__item kt-wizard-v2__aside">

                        <!--begin: Form Wizard Nav -->
                        <!--div class="kt-wizard-v2__nav">

                            <!--doc: Remove "kt-wizard-v2__nav-items--clickable" class and also set 'clickableSteps: false' in the JS init to disable manually clicking step titles -->
                            <!----div class="kt-wizard-v2__nav-items kt-wizard-v2__nav-items--clickable">
                                <div class="kt-wizard-v2__nav-item" data-ktwizard-type="step" data-ktwizard-state="current">
                                    <div class="kt-wizard-v2__nav-body">
                                        <div class="kt-wizard-v2__nav-icon">
                                            <i class="fa fa-pen"></i>
                                        </div>
                                        <div class="kt-wizard-v2__nav-label">
                                            <div class="kt-wizard-v2__nav-label-title">
                                                1. Modifier la demande
                                            </div>
                                            <div class="kt-wizard-v2__nav-label-desc">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                              

                            </!--div-->
                        <!----/div>

                        <!--end: Form Wizard Nav -->
                    <!----/-div-->
                    <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v2__wrapper">
                        <!--begin: Form Wizard Form-->
                        <div class="kt-form" id="kt_form">
                            <!----form class="kt-form" action="/Home/InsertUser" id="kt_form"-->
                            <!--begin: Form Wizard Step 1-->
                            <div class="kt-wizard-v2__content" data-ktwizard-type="step-content" data-ktwizard-state="current">
                                <div class="kt-heading kt-heading--md"></div>
                                <div class="kt-form__section kt-form__section--first">
                                    <div class="kt-wizard-v2__form">
                                        <div class="row">


                                            <div class="col-xl-6">
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.NoteDeFraisID)

                                                <div class="row">
                                                    <div class="col">
                                                        <label>Date de dépot <i class="fa fa-calendar"></i> </label>
                                                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @name = "date_entr", @id = "d_entre", @required = "Date de debut ", @disabled = "disabled" } })


                                                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                                        @Html.HiddenFor(model => model.Date)
                                                    </div>
                                                    
                                                    <div class="col">
                                                        <label>Type de frais  </label>
                                                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", @name = "date_anc", @id = "d_ancien", @required = "Date de fin", @disabled = "disabled" } })
                                                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                                        @Html.HiddenFor(model => model.Type)
                                                    </div>

                                                     <div class="col">
                                                        <label>Montant(en DT)<i class="fa fa-calendar"></i> </label>
                                                        @Html.EditorFor(model => model.Montant, new { htmlAttributes = new { @class = "form-control", @name = "date_anc", @id = "d_ancien", @required = "Date de fin", @disabled = "disabled" } })
                                                        @Html.ValidationMessageFor(model => model.Montant, "", new { @class = "text-danger" })
                                                        @Html.HiddenFor(model => model.Montant)
                                                    </div>
                                                     <div class="col">
                                                         <label>Nombre d'invités </label>
                                                         @Html.EditorFor(model => model.nbrper ,new { htmlAttributes = new { @class = "form-control", @name = "date_anc", @id = "d_ancien", @required = "Date de fin", @disabled = "disabled" } })
                                                         @Html.ValidationMessageFor(model => model.nbrper, "", new { @class = "text-danger" })
                                                         @Html.HiddenFor(model => model.nbrper)
                                                     </div>
                                                    <!----input type="date" class="form-control" name="date_entr" id="d_entre" required placeholder="Date de debut "-->
                                                </div>
                                            </div>

                                        </div>
                                        <div><p></p></div>
                                        <div class="row">
                                          
                                            <div class="col-xl-6">
                                                <div class="form-group">
                                                    <label>Votre Commentaire:</label>
                                                    @Html.TextAreaFor(model => model.CommentaireF, 5, 40, new { @class = "form-control", @name = "comm", @id = "comm_col", @required = "Votre commentaire...", @disabled = "disabled" })
                                                    @Html.ValidationMessageFor(model => model.CommentaireF, "", new { @class = "text-danger" })
                                                    @Html.HiddenFor(model => model.CommentaireF)
                                                    <!----textarea type="" class="form-control" id="comm_col" cols="40" rows="5" name="comm" required placeholder="Votre commentaire..."></!--textarea-->
                                                </div>
                                                <div class="form-group">
                                                    <label> Commentaire de la RH:</label>
                                                    @Html.TextAreaFor(model => model.CommentaireRH, 5, 40, new { @class = "form-control", @name = "comm", @id = "comm_col", @required = "Votre commentaire...", @disabled = "disabled" })
                                                    @Html.ValidationMessageFor(model => model.CommentaireRH, "", new { @class = "text-danger" })
                                                    @Html.HiddenFor(model => model.CommentaireRH)
                                                    <!----textarea type="" class="form-control" id="comm_col" cols="40" rows="5" name="comm" required placeholder="Votre commentaire..."></!--textarea-->
                                                </div>


                                            </div>

                                        </div>


                                        <div class="row">
                                            <div class="col-xl-6">
                                                <div class="form-group">
                                                    <label>Etat de la demande:</label>
                                                    @Html.DropDownListFor(model => model.Statut, new SelectList(new string[] { "Accepter", "Refuser", "à valider" }, "à valider"), htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                                                    @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })

                                                </div>
                                            </div>
                                            <div class="col-xl-6">
                                                <div class="form-group">
                                                    <label>Traitée par:</label>
                                                    @Html.EditorFor(model => model.RH, new { htmlAttributes = new { @class = "form-control", @name = "date_anc", @id = "d_ancien", @required = "Date de fin", @disabled = "disabled" } })
                                                    @Html.ValidationMessageFor(model => model.RH, "", new { @class = "text-danger" })
                                                    @Html.HiddenFor(model => model.RH)
                                                    <!----input type="date" class="form-control" name="date_anc" id="d_ancien" required placeholder="Date de fin"-->
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!--end: Form Wizard Step 1-->
                            <!--begin: Form Wizard Step 5-->
                            <!--end: Form Wizard Step 5-->
                            <!--begin: Form Wizard Step 6-->
                            <div class="kt-wizard-v2__content" data-ktwizard-type="step-content">
                                <div class="kt-heading kt-heading--md">validation</div>
                                <div class="kt-form__section kt-form__section--first">
                                    <div class="kt-wizard-v2__review">
                                        <div class="kt-wizard-v2__review-item">
                                            <div class="kt-wizard-v2__review-title">
                                                Demande de congé
                                            </div>
                                            <div class="kt-wizard-v2__review-content" id="inf_gen">

                                            </div>
                                        </div>




                                    </div>
                                </div>
                            </div>

                            <!--end: Form Wizard Step 6-->
                            <!--begin: Form Actions -->
                            @using (Html.BeginForm())
                            {
                                <div class="kt-form__actions">



                                    <input type="button" style="margin-left: 810px;" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2" value="Précédent" onclick="location.href='@Url.Action("Index", "Frais" )'" />


                                </div>
                                }
                                <!--end: Form Actions -->
                                <!----/form-->
                            </div>



                        <!--end: Form Wizard Form-->
                    </div>
                </div>
            </div>
        </div>

    </div>
}

SIRHCoreWeb/Areas/SIRH/Views/Frais/Index.cshtml
@model IEnumerable<SIRHCoreDomain.NoteDeFrais>

    @{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h1></h1>

    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-heading kt-heading--md">
            <center> <h1><font color="#273746">Consulter votre notes de frais </font></h1> </center>
        </div>
        <div class="kt-portlet">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                    <div class="kt-grid__item kt-wizard-v2__aside">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>

                        <form class="form-inline">
                            <div>
                                <div><div><p><label>    </label></p></div></div>
                            </div>
                            <div class="form-group mb-2">
                                <label class="form-group mx-sm-3 mb-2">Statut:</label>

                            </div>
                            <div class="form-group mx-sm-3 mb-2">

                                <input type="Text" class="form-control" name="search" placeholder="Filtrer selon le statut">


                            </div>
                            <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                        </form>

                        <div>
                            <div><div><p></p></div></div>
                        </div>
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>

                        <table class="table table-striped">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col"> ID </th>
                                    <th scope="col"> Type</th>
                                    <th scope="col"> Statut</th>
                                    <th scope="col"> Actions</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NoteDeFraisID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Type)
                                    </td>
                                   
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Statut)
                                    </td>

                                    <td>

                                        <i class="fa fa-trash" title="Supprimer" style="font-size:20px;color:#48C9B0;" onclick="location.href='@Url.Action("Delete", "Frais" , new { id=item.NoteDeFraisID })'"></i>



                                        <i class="fa fa-pen" title="Modifier" style="font-size:20px;color:#48C9B0;" onclick="location.href='@Url.Action("Edit", "Frais" , new { id=item.NoteDeFraisID })'"></i>
                                        <i class="fa fa-info" title="Details" style="font-size:20px;color:#48C9B0;" onclick="location.href='@Url.Action("Details", "Frais" , new { id=item.NoteDeFraisID })'"></i>



                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>

    </div>