SIRHCoreWeb/Areas/SIRH/Controllers/CollabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SIRHCoreData.Models.DB;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Controllers
{
    [Area("SIRH")]
    [Route("SIRH/[controller]/[action]")]
    public class CollabController : Controller
    {
        public CollabController(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            personneService = new PersonneService();
            projetService = new ProjetService();
            tachesService = new TachesService();
            incidentService = new IncidentService();
        }

        private readonly UserManager<IdentityUser> userManager;
        IProjetService projetService = null;
        IPersonneService personneService = null;
        ITachesService tachesService = null;
        IIncidentService incidentService = null;


        private DB_SIRHContext db = new DB_SIRHContext();

        public IActionResult Colab()
        {

            return View();
        }




        /********************************/



        public ActionResult projects(string search)
        {
            List<Projet> _projects = null;

            if (string.IsNullOrEmpty(search))
            {
                _projects = projetService.GetAll().ToList();

            }
            else
            {
                _projects = projetService.GetMany(x => x.nom.Contains(search) || x.description.Contains(search)).ToList();
            }

            return View(_projects);

        }



        public ActionResult myProjects(string search)
        {
            List<Projet> _projects = null;
            string name = User.Identity.Name;
            if (string.IsNullOrEmpty(search))
            {
                _projects = projetService.GetMany(x=> x.collaborateurs.Where(s => s.Personne.UserName == name).Any()).ToList();

            }
            else
            {
                _projects = projetService.GetMany(x =>x.collaborateurs.Where(s=>s.Personne.UserName==name).Any() && (x.nom.Contains(search) || x.description.Contains(search))).ToList();
            }

            return View(_projects);
        }


        public ActionResult DetailProject(int id)
        {
            Projet projet = projetService.GetProjet(id);
            CollaborateurService collaborateurService = new CollaborateurService();
            ViewBag.collab = personneService.GetMany(x => x.Collaborations.Where(s => s.Projet.id == id).Any());
            var collabs = userManager.GetUsersInRoleAsync("Collaborateur").Result;
            ViewBag.persons = collabs.Select(x =>
                   new SelectListItem { Value = x.UserName.ToString(), Text = x.UserName }

            ).ToList();
            string name = User.Identity.Name;
            ViewBag.iscollab = personneService.GetMany(x =>x.UserName==name && x.Collaborations.Where(s => s.Projet.id == id).Any()).Any();

            TachesService tachesService = new TachesService();
            ViewBag.taches = tachesService.GetTachesbyProjct(id);

            return View(projet);
        }




        [HttpGet]
        public ActionResult addTask(int projid)
        {
            Taches taches = new Taches();
            ViewBag.project = projid;
            return View(taches);
        }

        public ActionResult addTask(Taches taches, int projid)
        {
            ModelState.Remove("creator");
            ModelState.Remove("Projet");
            if (ModelState.IsValid)
            {
                string name = User.Identity.Name;
                taches.Projet = projetService.Get(x => x.id == projid);
                Personne personne = personneService.Get(x => x.UserName == name);




                taches.date = DateTime.Now;
                taches.state = "En cours";



                if (personne.Taches == null)
                {
                    personne.Taches = new List<Taches>();

                }
                personne.Taches.Add(taches);
                personneService.Update(personne);

                return RedirectToAction("DetailProject", new { id = projid });


            }
            else
            {
                ViewBag.project = projid;

                return View(taches);
            }
        }



        public ActionResult finishTask(int id)
        {
            Taches taches = tachesService.GetTaches(id);
            taches.state = "Terminé";
            tachesService.Update(taches);
            return RedirectToAction("DetailProject", new { id = taches.Projet.id });
        }




        /********************************/








        [HttpGet]
        public ActionResult addIncident()
        {
            Incident incident = new Incident();
            return View(incident);
        }


        [HttpPost]
        public ActionResult addIncident(Incident incident)
        {
            if (ModelState.IsValid)
            {
                incident.DateCreation = DateTime.Now;
                incident.status = "En cours";
                string name = User.Identity.Name;
                Personne personne = personneService.Get(x => x.UserName == name);
                if (personne.Incidents == null)
                {
                    personne.Incidents = new List<Incident>();
                }
                personne.Incidents.Add(incident);
                personneService.Update(personne);
                return RedirectToAction("mesIncident");

            }
            else
            {
                return View(incident);
            }
        }


        public ActionResult mesIncident( string search)
        {
            
            List<Incident> incidents = null;
            
         
                string name = User.Identity.Name;
                incidents = incidentService.GetUserIncident(name).ToList();

                if (!string.IsNullOrWhiteSpace(search))
                {
                    incidents = incidents.Where(x => x.Description.Contains(search) || x.status.Contains(search) || x.title.Contains(search)).ToList();
                }
         
 
                 

            return View(incidents);
        }


        public ActionResult deleteIncident(int id)
        {
            incidentService.Delete(x => x.Id == id);
            return RedirectToAction("mesIncident");
        }


        [HttpGet]
        public ActionResult editIncident(int id)
        {
            Incident incident = incidentService.Get(x => x.Id == id);
            return View(incident);

        }

        public ActionResult editIncident(Incident incident)
        {
            if (ModelState.IsValid)
            {

                incidentService.Update(incident);

                return RedirectToAction("mesIncident");

            }
            else
            {
                return View(incident);
            }
        }

        //i have to test these methods and add mark as treated


        public ActionResult markAsTreated(int incid,string treatement)
        {
            Incident incident1 = incidentService.Get(i => i.Id == incid);
            incident1.DateReglage = DateTime.Now;
            incident1.status = "Traité";
            incident1.Modifiepar = treatement;
            incidentService.Update(incident1);

            return RedirectToAction("toTreat");
        }

        public ActionResult toTreat()
        {
            string name = User.Identity.Name;
            List<Incident> incidents = incidentService.GetAffectedIncident(name).ToList();
            return View(incidents);
        }




        /********************************/





        public IActionResult ListColaborateur()
        {
            IEnumerable<TblDwSalarie> LS = db.TblDwSalarie.ToList();
            return View(LS);
        }

        public JsonResult listcolab()
        {
            List<TblDwSalarie> ls = db.TblDwSalarie.ToList();
            TblDwSalarie x = db.TblDwSalarie.FirstOrDefault(x => x.Matricule == 222);
            return Json(ls);
        }
        public IActionResult OnGetSelectDepartements()
        {
            IEnumerable<TblDimDepartement> user = db.TblDimDepartement.ToList();

            return new JsonResult(user);
        }

        public JsonResult GetResponsable()
        {
            List<TblDwSalarie> responsable = db.TblDwSalarie.Where(x => x.IdFonction == 4 || x.IdFonction == 5).ToList();

            return Json(responsable);
        }



        public IActionResult Index()
        {
            return View();
        }
        public bool InsertUser(string civilite, string name, string prenom, int matricule, int departement, string phone)
        {
            TblDwSalarie salarie = new TblDwSalarie();
            salarie.Civilite = civilite;
            salarie.Nom = name;
            salarie.Prenom = prenom;
            salarie.Email = "AAA";
            salarie.Tel = phone;
            salarie.Matricule = matricule;
            salarie.IdFonction = 1;
            salarie.IdStructure = 1;
            try
            {
                db.TblDwSalarie.Add(salarie);
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
        public bool InsertColab(string civilite, string name, string prenom, int matricule, int departement, string phone)
        {
            TblDwSalarie salarie = new TblDwSalarie();

            salarie.Civilite = civilite;
            salarie.Nom = name;
            salarie.Prenom = prenom;
            salarie.Email = "AAA";
            salarie.Tel = phone;
            salarie.Matricule = matricule;
            salarie.IdFonction = 1;
            salarie.IdStructure = 1;
            try
            {
                db.TblDwSalarie.Add(salarie);

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class CreateModel : PageModel
    {
        //injection du context

        private SIRHcontext db = new SIRHcontext();
        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public CreateModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }
        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DeleteModel : PageModel
         
    {//injection du context
        
        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DeleteModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }
       
          
        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DetailModel : PageModel
    {//injection du context

        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DetailModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }

        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Views/Collab/incidents.cshtml
@model IEnumerable<SIRHCoreDomain.Incident>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">Consulter toutes les projets </font></h1> </center>
    </div>

    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">


                    <form class="form-inline" method="post" action="@Url.Action("incidents","Collab")">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-group mx-sm-3 mb-2">     Recherche:</label>

                        </div>
                        <div class="form-group mx-sm-3 mb-2">

                            <input type="Text" class="form-control" name="search" placeholder="mot clé">


                        </div>

                        <div class="form-group mx-sm-3 mb-2">

                            <div class="radio-inline">
                                <label class="radio">
                                    <input type="radio" checked="checked" name="mine" value="false">
                                    <span></span>Tous
                                </label>
                                <label class="radio">
                                    <input type="radio" name="mine" value="true">
                                    <span></span>Mes
                                </label>

                            </div>


                        </div>

                        <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                    </form>




                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateCreation)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateReglage)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.status)
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DateCreation)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DateReglage)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    <span class="label label-xl label-inline label-light-success"> @Html.DisplayFor(modelItem => item.status) </span>
                                </td>
                                @{
                                    var attid="";
                                    if (item.Attribution != null)
                                    {
                                        attid = "exist";
                                    }
                                }

                                <td>
                                    @Html.ActionLink("Modifier", "editIncident", "Collab", new { id = item.Id }, new { @class = "btn btn-outline-primary" })  |
                                    <a href="" class="btn btn-outline-success" id="modalin" data-toggle="modal" data-target="#exampleModalLong"
                                       data-id="@item.Id"
                                       data-title="@item.title"
                                       data-creator="@item.Creepar.Nom @item.Creepar.Prenom"
                                       data-desc="@item.Description"
                                       data-datec="@item.DateCreation"
                                       data-dater="@item.DateReglage"
                                       data-aff="@attid">  Detail </a>
                                    @Html.ActionLink("Supprimer", "deleteIncident", "Collab", new { id = item.Id }, new { @class = "btn btn-outline-danger" })
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>


                </div>


            </div>
        </div>
    </div>

</div>


<div class="modal fade" id="exampleModalLong" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">



            </div>
            <div class="modal-footer  ">
         
                <div id="formaff" class="w-100">

                    <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                </div>
               
                 
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>

<script>
    $(document).on("click", "#modalin", function () {
        let datec = $(this).data("datec");
        let title = $(this).data("title");
        let creator = $(this).data("creator");
        let desc = $(this).data('desc');
        let dater = $(this).data('dater');
        let cid = $(this).data("id");
        let attrib = $(this).data("aff");
        console.log(cid);
       

        document.getElementById("inpid").value = cid;
      


        $('.modal-title').empty().append(title);
        $('.modal-body').empty().append("<p><br>Name: </br>" + creator + "</p><br><p><br>Date création: </br>" + datec + "</p><br>" + "<p><br>Date réglage: </br>" +
            dater + "</p><br><p><br>description: </br>" + desc + "</p>");
          
    });</script>

SIRHCoreWeb/Areas/SIRH/Views/Collab/mesIncident.cshtml
@model IEnumerable<SIRHCoreDomain.Incident>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">Consulter toutes les projets </font></h1> </center>
    </div>

    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">


                    <form class="form-inline" method="post" action="@Url.Action("mesIncident","Collab")">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-group mx-sm-3 mb-2">     Recherche:</label>

                        </div>
                        <div class="form-group mx-sm-3 mb-2">

                            <input type="Text" class="form-control" name="search" placeholder="mot clé">


                        </div>


                        <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                    </form>




                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateCreation)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateReglage)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.status)
                                </th>
                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateCreation)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateReglage)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @if (item.status == "En cours")
                                        {

                                            <span class="label label-xl label-inline label-light-success"> @Html.DisplayFor(modelItem => item.status) </span>
                                        }
                                        else
                                        {

                                            <span class="label label-xl label-inline label-light-primary"> @Html.DisplayFor(modelItem => item.status) </span>
                                        }
                                    </td>
                                    @{
                                        var attid = "";
                                        if (item.Attribution != null)
                                        {
                                            attid = "exist";
                                        }
                                    }

                                    <td>
                                        @Html.ActionLink("Modifier", "editIncident", "Collab", new { id = item.Id }, new { @class = "btn btn-outline-primary" })  |
                                        <a href="" class="btn btn-outline-success" id="modalin" data-toggle="modal" data-target="#exampleModalLong"
                                           data-id="@item.Id"
                                           data-title="@item.title"
                                           data-creator="@item.Creepar.Nom @item.Creepar.Prenom"
                                           data-desc="@item.Description"
                                           data-datec="@item.DateCreation"
                                           data-dater="@item.DateReglage"
                                           data-aff="@attid" data-treat="@item.Modifiepar">  Detail </a>
                                        @Html.ActionLink("Supprimer", "deleteIncident", "Collab", new { id = item.Id }, new { @class = "btn btn-outline-danger" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>


                </div>


            </div>
        </div>
    </div>

</div>


<div class="modal fade" id="exampleModalLong" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">



            </div>
            <div class="modal-footer  ">

                <div id="formaff" class="w-100">

                    <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                </div>


            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>

<script>
    $(document).on("click", "#modalin", function () {
        let datec = $(this).data("datec");
        let title = $(this).data("title");
        let creator = $(this).data("creator");
        let desc = $(this).data('desc');
        let dater = $(this).data('dater');
        let cid = $(this).data("id");
        let attrib = $(this).data("aff");
        let trait = $(this).data("treat");
        console.log(cid);


       // document.getElementById("inpid").value = cid;



        $('.modal-title').empty().append(title);
        $('.modal-body').empty().append("<p><br>Name: </br>" + creator + "</p><br><p><br>Date création: </br>" + datec + "</p><br>" + "<p><br>Date réglage: </br>" +
            dater + "</p><br><p><br>description: </br>" + desc + "</p><br><p><br>Traitement: </br>" + trait + "</p>");

    });</script>

SIRHCoreWeb/Areas/SIRH/Views/Collab/myProjects.cshtml
@model IEnumerable<SIRHCoreDomain.Projet>

@{
    ViewData["Title"] = "projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">Consulter toutes les projets </font></h1> </center>
    </div>

    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <form class="form-inline" method="post" action="@Url.Action("projects","Collab")">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-group mx-sm-3 mb-2">     Recherche:</label>

                        </div>
                        <div class="form-group mx-sm-3 mb-2">

                            <input type="Text" class="form-control" name="search" placeholder="mot clé">


                        </div>
                        <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                    </form>

                    <div>
                        <div><div><p></p></div></div>
                    </div>
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>
                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.nom)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.datedeb)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.datefin)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.createur)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.nom)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.datedeb)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.datefin)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.createur.Nom)
                                    </td>
                                    <td>

                                        @Html.ActionLink("Details", "DetailProject", "Collab", new { id = item.id }, new { @class = "btn btn-outline-success" })

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>


                </div>


            </div>
        </div>
    </div>

</div>