SIRHCoreWeb/Areas/SIRH/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using SIRHCoreService;
using SIRHCoreDomain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SIRHCoreWeb.Areas.SIRH.Controllers
{
    [Area("SIRH")]
    [Route("SIRH/[controller]/[action]")]
    [Authorize(Roles = "Responsable RH")]
    public class ManagerController : Controller


    {
        
      
      protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                service.Dispose();
            }
            base.Dispose(disposing);
        }

        private readonly UserManager<IdentityUser> userManager;

        public ManagerController(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            service = new CongeService();
            servicef = new FraisService();
            personneService = new PersonneService();
            projetService = new ProjetService();
            tachesService = new TachesService();
            incidentService = new IncidentService();
        }
        ICongeService service = null;
        IFraisService servicef = null;



        IProjetService projetService = null;
        IPersonneService personneService = null;
        ITachesService tachesService = null;
        IIncidentService incidentService = null;
        /************************************/


        [HttpGet]
        public ActionResult addProject()
        {
            Projet projet = new Projet();

            return View(projet);
        }
        [HttpPost]
        public ActionResult addProject(Projet projet)
        {
            ModelState.Remove("createur");
            if (ModelState.IsValid)
            {

                string name = User.Identity.Name;

                try
                {

                    projet.datedeb = DateTime.Now;
                    Personne personne = personneService.Get(x => x.UserName == name);
                    if (personne.Projets == null)
                    {
                        personne.Projets = new List<Projet>();
                    }
                    personne.Projets.Add(projet);
                    personneService.Update(personne);

                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }


            }
            else
            {
                return View(projet);
            }
            return Redirect("projects");


        }

        public ActionResult projects(string search)
        {
            List<Projet> _projects = null;

            if (string.IsNullOrEmpty(search))
            {
                _projects = projetService.GetAll().ToList();

            }
            else
            {
                _projects = projetService.GetMany(x => x.nom.Contains(search) || x.description.Contains(search)).ToList();
            }

            return View(_projects);

        }


        public ActionResult deleteProject(int id)
        {

            Projet _project = projetService.GetById(id);

            if (_project != null)
            {

                projetService.Delete(x => x.id == id);

            }
            return Redirect("projects");
        }


        [HttpGet]
        public ActionResult EditProject(long id)
        {
            Projet projet = projetService.Get(x => x.id == id);

            if (projet != null)
            {
                var collabs = userManager.GetUsersInRoleAsync("Collaborateur").Result;
                ViewBag.collabs = collabs.Select(x =>
                       new SelectListItem { Value = x.UserName.ToString(), Text = x.UserName }

                ).ToList();

                ViewBag.collaborateur = personneService.GetMany(x => x.Collaborations.Where(s => s.Projet.id == id).Any()).ToList();

                return View(projet);
            }
            else
            {
                return Redirect("projects");
            }
        }





        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditProject(Projet _projet)
        {

            if (ModelState.IsValid)
            {
                projetService.Update(_projet);

                return Redirect("projects");
            }
            else
            {
                return View(_projet);
            }


        }


        public ActionResult affectCollab(string username, int id, string rss)
        {
            if (id == 0)
            {
                if (!string.IsNullOrEmpty(rss))
                {
                    return RedirectToAction("DetailProject", new { id = id });
                }
                return RedirectToAction("Projects");
            }
            if (string.IsNullOrEmpty(username))
            {
                if (!string.IsNullOrEmpty(rss))
                {
                    return RedirectToAction("DetailProject", new { id = id });
                }
                return RedirectToAction("EditProject", new { id = id });
            }
            Projet projet = projetService.Get(x => x.id == id);
            Personne personne = personneService.Get(x => x.UserName == username);
            if (projet == null || personne == null)
            {
                if (!string.IsNullOrEmpty(rss))
                {
                    return RedirectToAction("DetailProject", new { id = id });
                }
                return RedirectToAction("EditProject", new { id = id });
            }
            
            
            
            Collaboration collaboration = new Collaboration();
            collaboration.Personne = personne;
            collaboration.Projet = projet;
           
            
            if (personne.Collaborations == null)
            {
                personne.Collaborations = new List<Collaboration>();
            }


            personne.Collaborations.Add(collaboration);
            personneService.Update(personne);
           
            
            
            
            if (!string.IsNullOrEmpty(rss))
            {
                return RedirectToAction("DetailProject", new { id = id });
            }


            return RedirectToAction("EditProject", new { id = id });
        }

        public ActionResult RemoveCollab(int projid, string userid, string rss)
        {
            if (projid == 0 || userid == "")
            {
                return RedirectToAction("Projects");
            }
            CollaborateurService collaborateurService = new CollaborateurService();
            collaborateurService.Delete(x => x.Personne.Id == userid.ToString() && x.Projet.id == projid);

            if (string.IsNullOrEmpty(rss))
            {

                return RedirectToAction("EditProject", new { id = projid });
            }
            else
            {
                return RedirectToAction("DetailProject", new { id = projid });
            }

        }


        public ActionResult DetailProject(int id)
        {
            Projet projet = projetService.GetProjet(id);
            CollaborateurService collaborateurService = new CollaborateurService();
            ViewBag.collab = personneService.GetMany(x => x.Collaborations.Where(s => s.Projet.id == id).Any());
            var collabs = userManager.GetUsersInRoleAsync("Collaborateur").Result;
            ViewBag.persons = collabs.Select(x =>
                   new SelectListItem { Value = x.UserName.ToString(), Text = x.UserName }

            ).ToList();
           
            
            
            TachesService tachesService = new TachesService();
            ViewBag.taches = tachesService.GetTachesbyProjct(id);

            return View(projet);
        }





        [HttpGet]
        public ActionResult addTask(int projid)
        {
            Taches taches = new Taches();
            ViewBag.project = projid;
            return View(taches);
        }

        public ActionResult addTask(Taches taches,int projid)
        {
            //remove it so that the modelstate will be valid
            ModelState.Remove("creator");
            ModelState.Remove("Projet");
            if (ModelState.IsValid)
            {
                //get the authenticated user username
                string name = User.Identity.Name;
                //get the project and assign it to the task we are going to create
                taches.Projet = projetService.Get(x => x.id == projid);
                Personne personne= personneService.Get(x => x.UserName == name);

               
                 
             
                taches.date = DateTime.Now;
                taches.state = "En cours";


                //the personne won't allow us to create the task without passing by the personne
                //we get the personne we add a task to him w update the personne that way task will be saved
                if (personne.Taches == null)
                {
                    personne.Taches = new List<Taches>();

                }
                //we add a task to a user and the upadte the user
                personne.Taches.Add(taches);
                personneService.Update(personne);

                return RedirectToAction("DetailProject", new { id = projid });


            }
            else
            {
                ViewBag.project = projid;

                return View(taches);
            }
        }



        public ActionResult finishTask(int id)
        {
            //update the task and make it closed
            Taches taches = tachesService.GetTaches(id);
            taches.state = "Terminé";
            tachesService.Update(taches);
            return RedirectToAction("DetailProject", new { id = taches.Projet.id });
        }






        [HttpGet]

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class CreateModel : PageModel
    {
        //injection du context

        private SIRHcontext db = new SIRHcontext();
        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public CreateModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }
        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DeleteModel : PageModel
         
    {//injection du context
        
        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DeleteModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }
       
          
        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Pages/Incidents/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIRHCoreData;
using SIRHCoreDomain;
using SIRHCoreService;

namespace SIRHCoreWeb.Areas.SIRH.Pages.Incidents
{
    public class DetailModel : PageModel
    {//injection du context

        private SIRHcontext db = new SIRHcontext();

        private readonly IIncidentService incidentService;
        [BindProperty]
        public Incident Incident { get; set; }
        public DetailModel(SIRHcontext context, IncidentService incservice)

        {
            incidentService = incservice;
            db = context;
        }

        public void OnGet()
        {
        }
    }
}

SIRHCoreWeb/Areas/SIRH/Views/Manager/CongeFrais.cshtml
@{
    ViewData["Title"] = "CongeFrais";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CongeFrais</h1>

SIRHCoreWeb/Areas/SIRH/Views/Manager/EditProject.cshtml
@model SIRHCoreDomain.Projet

@{
    ViewData["Title"] = "EditProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Modifier le projet @Model.nom
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-theme-6" })
        <div class="card-body">

            <div class="form-group">
                <label>Nom de projet</label>

                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "invalid-feedback" })

            </div>
            <div class="form-group ">
                <label class="">Date début de projet</label>


                @Html.EditorFor(model => model.datedeb, new { htmlAttributes = new { @class = "form-control", placeholder = " Date début de projet" } })

            </div>
            <div class="form-group ">
                <label class="">Date fin de projet</label>


                @Html.EditorFor(model => model.datefin, new { htmlAttributes = new { @class = "form-control", placeholder = " Date fin de projet" } })

            </div>

        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary mr-2">Submit</button>
            <button type="reset" class="btn btn-secondary">Cancel</button>
        </div>
    }

</div>


<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Affecter des collaborateur au projet @Model.nom
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
            </div>
        </div>
    </div>

    <div class="card-body">


        <div class="row">
            <label class="col-xl-3"></label>
            <div class="col-lg-9 col-xl-6">

            </div>
        </div>

        <div class="form-group row">
            <label class="col-xl-3 col-lg-3 col-form-label">Collaborateur</label>
            <div class="col-lg-9 col-xl-6">



                @using (Html.BeginForm("affectCollab", "Manager", "SIRH"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <div class="form-group row">
                        <div class="col-lg-4 col-md-9 col-sm-12">
                            @Html.DropDownList("username", ViewBag.collabs, "Select ...", htmlAttributes: new { @class = "form-control selectpicker" })
                        </div>

                        <input value="@Model.id" name="id" hidden="hidden" />

                        <div class="col-lg-5">
                            <input type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2" value="Affecter" />
                        </div>

                    </div>

                }
                <div class="message-success" style="color:darkred;">@ViewBag.ResultMessage</div>

            </div>
        </div>



    </div>

    <div class="card-footer">

    </div>

</div>



<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Liste des collaborateur au projet @Model.nom
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
            </div>
        </div>
    </div>

    <div class="card-body">


        <div class="row">
            <label class="col-xl-3"></label>
            <div class="col-lg-9 col-xl-6">

            </div>
        </div>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        Nom
                    </th>
                    <th>
                        Prenom
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Telephon
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.collaborateur)
                {
                    <tr>
                        <td>
                            @item.Nom
                        </td>
                        <td>
                            @item.Prenom
                        </td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.PhoneNumber
                        </td>
                        <td>
                            @Html.ActionLink("Retirer", "RemoveCollab", "Manager", new { projid = Model.id, userid = item.Id }, new { @class = "btn btn-outline-primary" })

                        </td>
                    </tr>
                }
            </tbody>
        </table>




    </div>

    <div class="card-footer">

    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SIRHCoreWeb/Areas/SIRH/Views/Manager/Lesdemandes.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<SIRHCoreDomain.Conge>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1></h1>

                
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">Consulter toutes ses demandes de Congés </font></h1> </center>
    </div>
    
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <form class="form-inline">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-group mx-sm-3 mb-2">     Statut:</label>

                        </div>
                        <div class="form-group mx-sm-3 mb-2">

                            <input type="Text" class="form-control" name="search" placeholder="Statut">


                        </div>
                        <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                    </form>

                    <div>
                        <div><div><p></p></div></div>
                    </div>
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col"> ID </th>
                                <th scope="col">  Date de début </th>
                                <th scope="col"> Date de fin</th>
                                <th scope="col"> Type</th>
                               
                               

                                <th scope="col"> Statut</th>
                                <th scope="col"> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CongeID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DateDeb)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DateFin)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.type)
                                </td>
                                
                                


                                <td>
                                    @Html.DisplayFor(modelItem => item.Statut)
                                </td>
                               

                                <td>
                                    <input type="button" style="color:#48C9B0;" class="btn btn-outline-dark" value="Traiter" onclick="location.href='@Url.Action("Reponse", "Manager", new { id = item.CongeID })'" />
                                
                                </td>

                            </tr>
                            }


                        </tbody>
                    </table>

                </div>
                @using (Html.BeginForm())
                {

                    <p>
                        <div class="kt-form__actions">

                            <i type="button" style="font-size:20px;color:#48C9B0;margin-left: 1000px;" class="fa fa-angle-double-left" value="Précédent" onclick="location.href='@Url.Action("ListUsers", "Manager" )'"></i>
                            
                        </div>
                        <!----input type="submit" value="Delete" /-->



                    </p>

                }

            </div>
        </div>
    </div>

</div>

SIRHCoreWeb/Areas/SIRH/Views/Manager/Lesfrais.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<SIRHCoreDomain.NoteDeFrais>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1></h1>

                
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">Consulter toutes ses notes de frais </font></h1> </center>
    </div>
    
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <form class="form-inline">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                        <div class="form-group mb-2">
                            <label class="form-group mx-sm-3 mb-2">     Type:</label>

                        </div>
                        <div class="form-group mx-sm-3 mb-2">

                            <input type="Text" class="form-control" name="search" placeholder="Statut">


                        </div>
                        <button type="submit" class="btn btn-success btn-md  btn-wide kt-font-bold kt-font-transform-u mb-2 ">Filtrer</button>
                    </form>

                    <div>
                        <div><div><p></p></div></div>
                    </div>
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col"> ID </th>
                                
                                <th scope="col"> Type</th>
                               
                               

                                <th scope="col"> Statut</th>
                                <th scope="col"> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NoteDeFraisID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Type)
                                </td>
                               
                               

                                <td>
                                    @Html.DisplayFor(modelItem => item.Statut)
                                </td>
                               

                                <td>
                                    <input type="button" style="color:#48C9B0;" class="btn btn-outline-dark" value="Traiter" onclick="location.href='@Url.Action("Reponsefrais", "Manager", new { id = item.NoteDeFraisID })'" />
                                
                                </td>

                            </tr>
                            }


                        </tbody>
                    </table>

                </div>
                @using (Html.BeginForm())
                {

                <p>
                    <div class="kt-form__actions">

                        <i type="button" style="font-size:20px;color:#48C9B0;margin-left: 1000px;" class="fa fa-angle-double-left" value="Précédent" onclick="location.href='@Url.Action(" ListUsers", "Manager" )'"></i>

                    </div>
                    <!----input type="submit" value="Delete" /-->



                </p>

                }

            </div>
        </div>
    </div>

</div>

SIRHCoreWeb/Areas/SIRH/Views/Manager/ListUsers.cshtml
@using Microsoft.AspNetCore.Identity

@model IEnumerable<IdentityUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1></h1>

<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="kt-heading kt-heading--md">
        <center> <h1><font color="#273746">La liste des utilisateurs </font></h1> </center>
    </div>
    <div class="kt-portlet">
        <div class="kt-portlet__body kt-portlet__body--fit">
            <div class="kt-grid  kt-wizard-v2 kt-wizard-v2--white" id="kt_wizard_v2" data-ktwizard-state="step-first">
                <div class="kt-grid__item kt-wizard-v2__aside">
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <form class="form-inline">
                        <div>
                            <div><div><p><label>    </label></p></div></div>
                        </div>
                      
                    </form>

                    <div>
                        <div><div><p></p></div></div>
                    </div>
                    <div>
                        <div><div><p><label>    </label></p></div></div>
                    </div>

                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col"><h5><center> Liste des employés</center> </h5></th>
                                <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                
                                <td sstyle="padding-left:50px">
                                    <i class="fas fa-user-tie " style="font-size:20px;">  </i>  @Html.DisplayFor(modelItem => item.UserName)
                                </td>


                                <td>
                                    <div class="btn-group dropleft">
                                        <i type="button" style="font-size:20px;color:#48C9B0;" class="fa fa-paperclip" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                        </i>
                                        <div class="dropdown-menu">

                                            <a class="dropdown-item" onclick="location.href='@Url.Action("Lesdemandes", "Manager", new { id=item.UserName })'">Les demandes des congés</a>
                                            <a class="dropdown-item" onclick="location.href='@Url.Action("Lesfrais", "Manager", new { id=item.UserName })'">Les demandes des Notes de frais</a>

                                            <a class="dropdown-item" onclick="location.href='@Url.Action("consltSolde", "Manager", new { id=item.UserName })'">Consulter le solde des congés</a>
                                        </div>
                                        
                                    </div>

                                   


                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>